CREATE TABLE IF NOT EXISTS projects (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS employees (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS tasks(
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    project_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE tasks
ADD FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS time_entries (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    duration INT DEFAULT 0,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    PRIMARY KEY(id)
);

ALTER TABLE time_entries
ADD FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;

ALTER TABLE time_entries
ADD FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;